export const COLORS = {
  white: '#ffffff',
  black: '#000000',
  cricDark: '#171a1fff',
  cricPrimary: '#6d31ed',
  cricPrimaryLight: '#6d31ed7d',
  cricError: '#d32f2f',
  cricLabel: '#CACDD4F',
  inputBg: '#f3f4f6',
  placeholder: '#949495',
  asterisk: '#f00',
  statusBg: {
    upcoming: '#eb006eb3',
    preauction: '#0042ebb5',
    inauction: '#a92effbf',
    inprogress: '#6d31ed',
    completed: '#eb0000b3',
  },
  statusTxt: {
    upcoming: '#ffffff',
    preauction: '#ffffff',
    inauction: '#ffffff',
    inprogress: '#ffffff',
    completed: '#ffffff',
  },
}
