export const API_URL = 'https://crickccservice.onrender.com/api/'
export const HEALTH_URL = 'health'
export const LOGIN_URL = 'users/login'
export const SIGNUP_URL = 'users'
export const TOURNAMENT_URL = 'tournament'
