#!/bin/sh

# Inspects branch name and checks if it contains a Jira ticket number (i.e. ABC-123).
# If yes, commit message will be automatically prepended with [ABC-123].
#
# Useful for looking through git history and relating a commit or group of commits
# back to a user story.

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

# Ensure BRANCH_NAME is not empty and is not in a detached HEAD state (i.e. rebase).
# SKIP_PREPARE_COMMIT_MSG may be used as an escape hatch to disable this hook,
# while still allowing other githooks to run.
if [ ! -z "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "HEAD" ] && [ "$SKIP_PREPARE_COMMIT_MSG" != 1 ]; then

  # Define a prefix pattern for Jira ticket numbers (e.g., ABC-123)
  PREFIX_PATTERN='[A-Z]{2,5}-[0-9]{1,4}'

  # Check if the branch name matches the pattern
  if [[ $BRANCH_NAME =~ $PREFIX_PATTERN ]]; then
    PREFIX=${BASH_REMATCH[0]}
  fi

  # Check if the prefix already exists in the commit message
  PREFIX_IN_COMMIT=$(grep -c "\[$PREFIX\]" "$1")

  # If the prefix is found in the branch and not in the commit message, prepend it
  if [ -n "$PREFIX" ] && [ "$PREFIX_IN_COMMIT" -eq 0 ]; then
    # Ensure compatibility with Windows by handling the file differently
    if [ -z "$(which sed)" ]; then
      echo "No sed available, amending commit manually..."
      git commit --amend --no-edit -m "$PREFIX $(cat $1)"
    else
      # Use sed for Unix-like systems
      sed -i -e "1s/^/$PREFIX /" "$1"
    fi
  fi

fi